name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          diagnostic-endpoint: ""
          source-url: "https://install.lix.systems/lix/lix-installer-x86_64-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@v9
        with:
          diagnostic-endpoint: ""
      - run: nix -Lv flake check
  
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          lfs: true
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          diagnostic-endpoint: ""
          source-url: "https://install.lix.systems/lix/lix-installer-x86_64-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@v9
        with:
          diagnostic-endpoint: ""
      - name: Create initial tag
        run: |
          if [ -z "$(git tag -l 'v*')" ]; then
            git tag v0.0.0
          fi

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: 'patch'

      - run: nix -Lv build .#slides

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: Version ${{ steps.bump.outputs.new_tag }}
          draft: false
          prerelease: false
          files: |
            ./result/main.pdf
